### ISSUE TITLE
A few files still import from PyQt4

### ISSUE THREAD

**Issue by borysiasty** [axelande/geodatafarm3#1]
They are:  
  - database_scripts/mean_analyse.py
  - widgets/thred_testar.py
  - resources.py  (use pyrrc5 and pyuic5 for compiling resources and ui files) 

As QGIS 3 is based on Qt5, you should use PyQt5 instead. I even can't run your plugin, as I only keep python2-PyQt4 and python3-PyQt5.

**Comment by axelande** [comment]
I know that I should use PyQt5 :), I changed changed that and rebuild resources with pyrrc5, still not reloading the more than main python file :(

The log message here shows:
2018-02-23T22:24:54	INFO	 : <b>geodatafarm</b> reloaded.
2018-02-23T22:31:10	WARNING	Python error : Couldn't load plugin 'geodatafarm' due to an error when calling its classFactory() method See message log (Python Error) for more details.
2018-02-23T22:31:10	INFO	 : <b>geodatafarm</b> reloaded.
2018-02-23T22:31:39	INFO	 : <b>geodatafarm</b> reloaded.

The first time there was no changes in the files when I reloaded them, 
the second time i deliberately corrupted the main python file, and it failed to load, 
the third time I fixed the main python file and deliberately corrupted another file and log doesn't complain about it. I restart QGIS and the plugin fails to load.

It feels like I have an error, plugin reloder reload until something fails, hence instead of stating where it is wrong it "finish" the reloading and produce no error, or?

* btw thx for taking a look at my problem!

**Comment by borysiasty** [comment]
> It feels like I have an error, plugin reloder reload until something fails, hence instead of stating where it
> is wrong it "finish" the reloading and produce no error, or?

Not exactly. Python doesn't seem to be designed to reload modules on the fly. It doesn't return any feedback, thus the reloader doesn't know if reloading was effective. In your third case reloading of the broken file didn't really occur, so no error was called. And the reloader just confirmed that after requesting reloading `` __init__.py `` with its dependencies it didn't get any errors. See all the issues with reloading complex plugins that still have to be fixed somehow - hopefully later this year. 

Coming back to your problem... It's simple :) Instead of 

```
sys.path.append(os.path.dirname(__file__))
```

just import like that:

```
from . import resources
from .GeoDataFarm_dockwidget import GeoDataFarmDockWidget
```

And the same recursively in those imported files. Actually you did it in ``__init__.py`` when importing GeoDataFarm, and it's why only GeoDataFarm.py is being effectively reloaded.
